// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Runner.Runner.Outputs
{

    [OutputType]
    public sealed class CommandDefinition
    {
        public readonly string Command;
        public readonly ImmutableDictionary<string, string>? Environment;
        public readonly ImmutableArray<Outputs.FileAsset> Payload;

        [OutputConstructor]
        private CommandDefinition(
            string command,

            ImmutableDictionary<string, string>? environment,

            ImmutableArray<Outputs.FileAsset> payload)
        {
            Command = command;
            Environment = environment;
            Payload = payload;
        }
    }
}
