// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Runner.Runner.Outputs
{

    [OutputType]
    public sealed class Config
    {
        public readonly int? AptLockTimeout;
        public readonly bool? KeepPayload;
        public readonly ABKLabs.Runner.Deb.Outputs.PackageConfig? PackageConfig;

        [OutputConstructor]
        private Config(
            int? aptLockTimeout,

            bool? keepPayload,

            ABKLabs.Runner.Deb.Outputs.PackageConfig? packageConfig)
        {
            AptLockTimeout = aptLockTimeout;
            KeepPayload = keepPayload;
            PackageConfig = packageConfig;
        }
    }
}
