// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Runner.Runner.Outputs
{

    [OutputType]
    public sealed class FileAsset
    {
        public readonly string? Contents;
        public readonly string? Filename;
        public readonly string? LocalPath;
        public readonly int? Mode;

        [OutputConstructor]
        private FileAsset(
            string? contents,

            string? filename,

            string? localPath,

            int? mode)
        {
            Contents = contents;
            Filename = filename;
            LocalPath = localPath;
            Mode = mode;
        }
    }
}
