// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Runner.Runner.Inputs
{

    public sealed class CommandDefinitionArgs : global::Pulumi.ResourceArgs
    {
        [Input("command", required: true)]
        public Input<string> Command { get; set; } = null!;

        [Input("environment")]
        private InputMap<string>? _environment;
        public InputMap<string> Environment
        {
            get => _environment ?? (_environment = new InputMap<string>());
            set => _environment = value;
        }

        [Input("payload")]
        private InputList<Inputs.FileAssetArgs>? _payload;
        public InputList<Inputs.FileAssetArgs> Payload
        {
            get => _payload ?? (_payload = new InputList<Inputs.FileAssetArgs>());
            set => _payload = value;
        }

        public CommandDefinitionArgs()
        {
        }
        public static new CommandDefinitionArgs Empty => new CommandDefinitionArgs();
    }
}
