// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Runner.Runner.Inputs
{

    public sealed class FileAssetArgs : global::Pulumi.ResourceArgs
    {
        [Input("contents")]
        public Input<string>? Contents { get; set; }

        [Input("filename")]
        public Input<string>? Filename { get; set; }

        [Input("localPath")]
        public Input<string>? LocalPath { get; set; }

        [Input("mode")]
        public Input<int>? Mode { get; set; }

        public FileAssetArgs()
        {
        }
        public static new FileAssetArgs Empty => new FileAssetArgs();
    }
}
