// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace ABKLabs.Runner.Runner
{
    public static class LocalFile
    {
        public static Task<LocalFileResult> InvokeAsync(LocalFileArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<LocalFileResult>("runner:runner:localFile", args ?? new LocalFileArgs(), options.WithDefaults());

        public static Output<LocalFileResult> Invoke(LocalFileInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<LocalFileResult>("runner:runner:localFile", args ?? new LocalFileInvokeArgs(), options.WithDefaults());

        public static Output<LocalFileResult> Invoke(LocalFileInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<LocalFileResult>("runner:runner:localFile", args ?? new LocalFileInvokeArgs(), options.WithDefaults());
    }


    public sealed class LocalFileArgs : global::Pulumi.InvokeArgs
    {
        [Input("contents")]
        public string? Contents { get; set; }

        [Input("filename")]
        public string? Filename { get; set; }

        [Input("localPath")]
        public string? LocalPath { get; set; }

        [Input("mode")]
        public int? Mode { get; set; }

        public LocalFileArgs()
        {
        }
        public static new LocalFileArgs Empty => new LocalFileArgs();
    }

    public sealed class LocalFileInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("contents")]
        public Input<string>? Contents { get; set; }

        [Input("filename")]
        public Input<string>? Filename { get; set; }

        [Input("localPath")]
        public Input<string>? LocalPath { get; set; }

        [Input("mode")]
        public Input<int>? Mode { get; set; }

        public LocalFileInvokeArgs()
        {
        }
        public static new LocalFileInvokeArgs Empty => new LocalFileInvokeArgs();
    }


    [OutputType]
    public sealed class LocalFileResult
    {
        public readonly string? Contents;
        public readonly string? Filename;
        public readonly string? LocalPath;
        public readonly int? Mode;

        [OutputConstructor]
        private LocalFileResult(
            string? contents,

            string? filename,

            string? localPath,

            int? mode)
        {
            Contents = contents;
            Filename = filename;
            LocalPath = localPath;
            Mode = mode;
        }
    }
}
