// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package runner

import (
	"context"
	"reflect"

	"github.com/abklabs/pulumi-runner/sdk/go/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LocalFile(ctx *pulumi.Context, args *LocalFileArgs, opts ...pulumi.InvokeOption) (*LocalFileResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LocalFileResult
	err := ctx.Invoke("runner:runner:localFile", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LocalFileArgs struct {
	Contents  *string `pulumi:"contents"`
	Filename  *string `pulumi:"filename"`
	LocalPath *string `pulumi:"localPath"`
	Mode      *int    `pulumi:"mode"`
}

type LocalFileResult struct {
	Contents  *string `pulumi:"contents"`
	Filename  *string `pulumi:"filename"`
	LocalPath *string `pulumi:"localPath"`
	Mode      *int    `pulumi:"mode"`
}

func LocalFileOutput(ctx *pulumi.Context, args LocalFileOutputArgs, opts ...pulumi.InvokeOption) LocalFileResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LocalFileResultOutput, error) {
			args := v.(LocalFileArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("runner:runner:localFile", args, LocalFileResultOutput{}, options).(LocalFileResultOutput), nil
		}).(LocalFileResultOutput)
}

type LocalFileOutputArgs struct {
	Contents  pulumi.StringPtrInput `pulumi:"contents"`
	Filename  pulumi.StringPtrInput `pulumi:"filename"`
	LocalPath pulumi.StringPtrInput `pulumi:"localPath"`
	Mode      pulumi.IntPtrInput    `pulumi:"mode"`
}

func (LocalFileOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LocalFileArgs)(nil)).Elem()
}

type LocalFileResultOutput struct{ *pulumi.OutputState }

func (LocalFileResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LocalFileResult)(nil)).Elem()
}

func (o LocalFileResultOutput) ToLocalFileResultOutput() LocalFileResultOutput {
	return o
}

func (o LocalFileResultOutput) ToLocalFileResultOutputWithContext(ctx context.Context) LocalFileResultOutput {
	return o
}

func (o LocalFileResultOutput) Contents() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LocalFileResult) *string { return v.Contents }).(pulumi.StringPtrOutput)
}

func (o LocalFileResultOutput) Filename() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LocalFileResult) *string { return v.Filename }).(pulumi.StringPtrOutput)
}

func (o LocalFileResultOutput) LocalPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LocalFileResult) *string { return v.LocalPath }).(pulumi.StringPtrOutput)
}

func (o LocalFileResultOutput) Mode() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LocalFileResult) *int { return v.Mode }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LocalFileResultOutput{})
}
