// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function localFile(args?: LocalFileArgs, opts?: pulumi.InvokeOptions): Promise<LocalFileResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("runner:runner:localFile", {
        "contents": args.contents,
        "filename": args.filename,
        "localPath": args.localPath,
        "mode": args.mode,
    }, opts);
}

export interface LocalFileArgs {
    contents?: string;
    filename?: string;
    localPath?: string;
    mode?: number;
}

export interface LocalFileResult {
    readonly contents?: string;
    readonly filename?: string;
    readonly localPath?: string;
    readonly mode?: number;
}
export function localFileOutput(args?: LocalFileOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<LocalFileResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("runner:runner:localFile", {
        "contents": args.contents,
        "filename": args.filename,
        "localPath": args.localPath,
        "mode": args.mode,
    }, opts);
}

export interface LocalFileOutputArgs {
    contents?: pulumi.Input<string>;
    filename?: pulumi.Input<string>;
    localPath?: pulumi.Input<string>;
    mode?: pulumi.Input<number>;
}
